{pkgs}: {
  deps = [
    pkgs.binutils
    pkgs.patchelf
    pkgs.glibc
    pkgs.libgcc
    pkgs.gcc
    pkgs.zlib
    pkgs.harfbuzz
    pkgs.xorg.libxkbfile
    pkgs.xorg.libXScrnSaver
    pkgs.xorg.libXcursor
    pkgs.xorg.libXinerama
    pkgs.xorg.libXtst
    pkgs.xorg.libXi
    pkgs.gio-sharp
    pkgs.polkit
    pkgs.openssl
    pkgs.xterm
    pkgs.xvfb-run
    pkgs.xorg.xorgserver
    pkgs.chromium
    pkgs.freetype
    pkgs.fontconfig
    pkgs.expat
    pkgs.xorg.libXrender
    pkgs.xorg.libXau
    pkgs.xorg.libX11
    pkgs.xorg.libXext
    pkgs.xorg.libXfixes
    pkgs.gtk3
    pkgs.gdk-pixbuf
    pkgs.glib
    pkgs.cairo
    pkgs.pango
    pkgs.dbus
    pkgs.cups
    pkgs.at-spi2-atk
    pkgs.xorg.libxcb
    pkgs.xorg.libXrandr
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.libxkbcommon
    pkgs.mesa
    pkgs.libdrm
    pkgs.alsa-lib
    pkgs.nspr
    pkgs.nss
    pkgs.ffmpeg
  ];
}
